apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jenkins
  name: jenkins
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: jenkinsci:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "2"
              memory: "2048Mi"
            requests:
              cpu: "1"
              memory: "1024Mi"
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 50000
              protocol: TCP
          volumeMounts:
            - name: jenkins-data
              mountPath: /var/jenkins_home
            # - name: volume-localtime
            #   mountPath: /etc/localtime
            - name: volume-docker
              mountPath: /var/run/docker.sock
      securityContext:
        fsGroup: 1000
      volumes:
        - name: jenkins-data
          persistentVolumeClaim:
            claimName: jenkins-pvc
            readOnly: false
        # - name: volume-localtime
        #   hostPath:
        #     path: /etc/localtime
        #     type: ''
        - name: volume-docker
          hostPath:
            path: /var/run/docker.sock
            type: ''
      imagePullSecrets:
        - name: your-registry-secret

# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: it-jenkins-boot
#   labels:
#     app: it-jenkins-boot
#   namespace: default
# spec:
#   ports:
#     - port: 8081
#       targetPort: 8081
#       name: it-jenkins-boot-svc
#   type: ClusterIP
#   selector:
#     app: it-jenkins-boot

# ---

# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: jenkins-boot-ingress
#   annotations:
#     kubernetes.io/ingress.class: "nginx"
#     nginx.ingress.kubernetes.io/rewrite-target: /$2
#   namespace: default
# spec:
#   rules:
#     - http:
#         paths:
#           - path: /jenkins-boot(/|$)(.*)
#             pathType: Prefix
#             backend:
#               service:
#                 name: it-jenkins-boot
#                 port:
#                   number: 8081